name: gitterapi
version: 0.1.0-b
description: A Dart client library for accessing Gitter API..
repository: https://github.com/RatakondalaArun/gitterapi
issue_tracker: https://github.com/RatakondalaArun/gitterapi/issues
homepage: https://github.com/RatakondalaArun/gitterapi

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  meta: ^1.2.4

dev_dependencies:
  test: ^1.15.7
  dotenv: ^2.0.0
  dartdoc: ^0.38.0
  dhttpd: ^3.0.2
