name: gitterapi
description: Gitter API warpper.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  meta: ^1.2.4

dev_dependencies:
  test: ^1.15.7
  dotenv: ^2.0.0
  dartdoc: ^0.38.0
